# Generated by Django 5.0.8 on 2024-08-22 09:04

import functools

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import dash.utils


def generate_initial_block_types(apps, schema_editor):
    User = apps.get_model("auth", "User")
    root = User.objects.filter(username="root").first()

    if not root:
        root = User.objects.filter(username="root2").first()

        if not root:
            root = User.objects.create(username="root2")

    DashBlockType = apps.get_model("dashblocks", "DashBlockType")

    DashBlockType.objects.get_or_create(
        name="About",
        slug="about",
        description="About pages by highest priority",
        has_title=True,
        has_image=True,
        has_rich_text=False,
        has_summary=False,
        has_link=False,
        has_gallery=False,
        has_color=False,
        has_video=False,
        has_tags=False,
        created_by=root,
        modified_by=root,
    )

    DashBlockType.objects.get_or_create(
        name="Join & Engage",
        slug="join_engage",
        description="Join & Engage by highest priority",
        has_title=True,
        has_image=True,
        has_rich_text=False,
        has_summary=False,
        has_link=False,
        has_gallery=False,
        has_color=False,
        has_video=False,
        has_tags=False,
        created_by=root,
        modified_by=root,
    )

    DashBlockType.objects.get_or_create(
        name="YouTube Videos",
        slug="youtube_videos",
        description="YouTube Videos to embed on the website",
        has_title=True,
        has_image=False,
        has_rich_text=False,
        has_summary=False,
        has_link=False,
        has_gallery=False,
        has_color=False,
        has_video=True,
        has_tags=False,
        created_by=root,
        modified_by=root,
    )

    DashBlockType.objects.get_or_create(
        name="U-Reporters",
        slug="ureporters",
        description="U-Reporters Page",
        has_title=True,
        has_image=True,
        has_rich_text=False,
        has_summary=False,
        has_link=False,
        has_gallery=False,
        has_color=False,
        has_video=False,
        has_tags=False,
        created_by=root,
        modified_by=root,
    )

    DashBlockType.objects.get_or_create(
        name="Missions",
        slug="missions",
        description="U-Report missions blocks",
        has_title=True,
        has_image=True,
        has_rich_text=False,
        has_summary=False,
        has_link=False,
        has_gallery=False,
        has_color=False,
        has_video=False,
        has_tags=False,
        created_by=root,
        modified_by=root,
    )

    DashBlockType.objects.get_or_create(
        name="Contact Us",
        slug="contact_us",
        description="U-Report contact us blocks",
        has_title=True,
        has_image=False,
        has_rich_text=False,
        has_summary=False,
        has_link=False,
        has_gallery=False,
        has_color=False,
        has_video=False,
        has_tags=False,
        created_by=root,
        modified_by=root,
    )

    DashBlockType.objects.get_or_create(
        name="Join Steps",
        slug="join_steps",
        description="U-Report join steps",
        has_title=True,
        has_image=True,
        has_rich_text=False,
        has_summary=False,
        has_link=False,
        has_gallery=False,
        has_color=False,
        has_video=False,
        has_tags=False,
        created_by=root,
        modified_by=root,
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    replaces = [
        ("dashblocks", "0001_initial"),
        ("dashblocks", "0002_auto_20140802_2112"),
        ("dashblocks", "0003_auto_20140804_0236"),
        ("dashblocks", "0004_auto_20140902_1200"),
        ("dashblocks", "0005_auto_20140904_0957"),
        ("dashblocks", "0006_auto_20140922_1514"),
        ("dashblocks", "0007_auto_20170301_0914"),
        ("dashblocks", "0008_auto_20210902_1125"),
        ("dashblocks", "0009_auto_20210910_1450"),
        ("dashblocks", "0010_alter_dashblock_created_by_and_more"),
        ("dashblocks", "0011_alter_dashblock_index_together_and_more"),
        (
            "dashblocks",
            "0012_rename_dashblock_org_is_active_dashblock_type_priority_dashblocks__org_id_024805_idx_and_more",
        ),
        ("dashblocks", "0013_rename_dashblocks__org_id_024805_idx_dashblock_org_typ_prio_idx_and_more"),
    ]

    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
        ("orgs", "0031_alter_orgbackend_index_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashBlock",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, help_text="When this item was originally created"),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, help_text="When this item was last modified")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="The title for this block of content, optional",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, help_text="The summary for this item, should be short", null=True),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="The body of text for this content block, optional", null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Any image that should be displayed with this content block, optional",
                        null=True,
                        upload_to="dashblocks",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="A background color to use for the image, in the format: #rrggbb",
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Any link that should be associated with this content block, optional",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        blank=True,
                        help_text="The id of the YouTube video that should be linked to this item",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Any tags for this content block, separated by spaces, can be used to do more advanced filtering, optional",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="The priority for this block, higher priority blocks come first"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="The organization this content block belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orgs.org",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DashBlockImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, help_text="When this item was originally created"),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, help_text="When this item was last modified")),
                (
                    "image",
                    models.ImageField(height_field="height", upload_to="dashblock_images/", width_field="width"),
                ),
                ("caption", models.CharField(max_length=64)),
                ("priority", models.IntegerField(blank=True, default=0, null=True)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dashblock",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="dashblocks.dashblock"),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DashBlockType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, help_text="When this item was originally created"),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, help_text="When this item was last modified")),
                (
                    "name",
                    models.CharField(
                        help_text="The human readable name for this content type", max_length=75, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug to idenfity this content type, used with the template tags", unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A description of where this content type is used on the site and how it will be dsiplayed",
                        null=True,
                    ),
                ),
                (
                    "has_title",
                    models.BooleanField(default=True, help_text="Whether this content should include a title"),
                ),
                (
                    "has_image",
                    models.BooleanField(default=True, help_text="Whether this content should include an image"),
                ),
                (
                    "has_rich_text",
                    models.BooleanField(default=True, help_text="Whether this content should use a rich HTML editor"),
                ),
                (
                    "has_summary",
                    models.BooleanField(default=True, help_text="Whether this content should include a summary field"),
                ),
                (
                    "has_link",
                    models.BooleanField(default=True, help_text="Whether this content should include a link"),
                ),
                (
                    "has_gallery",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this content should allow upload of additional images, ie a gallery",
                    ),
                ),
                ("has_color", models.BooleanField(default=False, help_text="Whether this content has a color field")),
                (
                    "has_video",
                    models.BooleanField(
                        default=False, help_text="Whether this content should allow setting a YouTube id"
                    ),
                ),
                ("has_tags", models.BooleanField(default=False, help_text="Whether this content should allow tags")),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="dashblock",
            name="dashblock_type",
            field=models.ForeignKey(
                help_text="The category, or type for this content block",
                on_delete=django.db.models.deletion.PROTECT,
                to="dashblocks.dashblocktype",
                verbose_name="Content Type",
            ),
        ),
        migrations.RunPython(code=generate_initial_block_types, reverse_code=noop),
        migrations.AlterField(
            model_name="dashblock",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dashblocks_dashblock_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dashblock",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dashblocks_dashblock_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dashblockimage",
            name="dashblock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="images", to="dashblocks.dashblock"
            ),
        ),
        migrations.AlterField(
            model_name="dashblocktype",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dashblocks_dashblocktype_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dashblocktype",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dashblocks_dashblocktype_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dashblock",
            name="created_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was originally created",
            ),
        ),
        migrations.AlterField(
            model_name="dashblock",
            name="modified_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was last modified",
            ),
        ),
        migrations.AlterField(
            model_name="dashblockimage",
            name="created_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was originally created",
            ),
        ),
        migrations.AlterField(
            model_name="dashblockimage",
            name="modified_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was last modified",
            ),
        ),
        migrations.AlterField(
            model_name="dashblocktype",
            name="created_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was originally created",
            ),
        ),
        migrations.AlterField(
            model_name="dashblocktype",
            name="modified_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was last modified",
            ),
        ),
        migrations.AlterModelOptions(
            name="dashblock",
            options={"ordering": ["dashblock_type", "title"]},
        ),
        migrations.AlterModelOptions(
            name="dashblocktype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="dashblock",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Any image that should be displayed with this content block, optional",
                null=True,
                upload_to=functools.partial(dash.utils.generate_file_path, *("dashblocks",), **{}),
            ),
        ),
        migrations.AlterField(
            model_name="dashblockimage",
            name="image",
            field=models.ImageField(
                height_field="height",
                upload_to=functools.partial(dash.utils.generate_file_path, *("dashblock_images/",), **{}),
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="dashblock",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dashblock",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dashblockimage",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dashblockimage",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dashblocktype",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dashblocktype",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="dashblock",
            index=models.Index(
                fields=["org", "is_active", "dashblock_type", "priority"], name="dashblock_org_typ_prio_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashblocktype", index=models.Index(fields=["slug", "name"], name="dashblocktype_slug_name_idx")
        ),
    ]
