# Generated by Django 3.2.6 on 2021-09-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashblocks", "0007_auto_20170301_0914"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashblock",
            options={"ordering": ["dashblock_type", "title"]},
        ),
        migrations.AlterModelOptions(
            name="dashblocktype",
            options={"ordering": ["name"]},
        ),
    ]
