# Generated by Django 5.2.14 on 2026-07-27 11:32

import dash.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashblocks",
            "0013_rename_dashblocks__org_id_024805_idx_dashblock_org_typ_prio_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashblockimage",
            name="image",
            field=models.ImageField(
                height_field="height",
                upload_to=functools.partial(
                    dash.utils.generate_file_path, *("dashblock_images",), **{}
                ),
                width_field="width",
            ),
        ),
    ]
