# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0024_populate_org_backend'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orgbackend',
            unique_together=set([('org', 'slug')]),
        ),
    ]
