# Generated by Django 3.2.6 on 2021-08-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0026_fix_org_config_rapidpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='config',
            field=models.JSONField(default=dict, help_text='JSON blob used to store configuration information associated with this organization'),
        ),
    ]
