# Generated by Django 4.1.7 on 2023-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0030_alter_invitation_created_by_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="orgbackend",
            index=models.Index(fields=["org", "is_active", "slug"], name="orgs_orgbac_org_id_607508_idx"),
        ),
    ]
