# Generated by Django 4.2.1 on 2023-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0031_alter_orgbackend_index_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
    ]
