# Generated by Django 5.0.8 on 2024-08-22 09:00

import functools

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import dash.stories.models
import dash.utils


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# dash.stories.migrations.0004_auto_20140806_1540
def populate_story_summary(apps, schema_editor):
    Story = apps.get_model("stories", "Story")
    for story in Story.objects.all():
        story.summary = story.content
        story.save()


# dash.stories.migrations.0006_auto_20140821_0859
def add_category_to_current_stories(apps, schema_editor):
    Story = apps.get_model("stories", "Story")
    Category = apps.get_model("categories", "Category")

    for story in Story.objects.all():
        general_category = Category.objects.get(name__icontains="general", org=story.org)
        story.category = general_category
        story.save()


# dash.stories.migrations.0008_auto_20140912_0524
def move_images(apps, schema_editor):
    # for each story we want to move any image currently on it and instead create a StoryImage for it
    Story = apps.get_model("stories", "Story")
    StoryImage = apps.get_model("stories", "StoryImage")

    for story in Story.objects.exclude(image=None):
        StoryImage.objects.create(
            story=story, image=story.image, created_by=story.created_by, modified_by=story.modified_by
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    replaces = [
        ("stories", "0001_initial"),
        ("stories", "0002_auto_20140805_1158"),
        ("stories", "0003_story_summary"),
        ("stories", "0004_auto_20140806_1540"),
        ("stories", "0005_story_category"),
        ("stories", "0006_auto_20140821_0859"),
        ("stories", "0007_storyimage"),
        ("stories", "0008_auto_20140912_0524"),
        ("stories", "0009_remove_story_image"),
        ("stories", "0010_auto_20140922_1514"),
        ("stories", "0011_story_audio_link"),
        ("stories", "0012_story_written_by"),
        ("stories", "0013_auto_20170301_0914"),
        ("stories", "0014_alter_storyimage_image"),
        ("stories", "0015_story_attachment"),
        ("stories", "0016_alter_story_created_by_alter_story_modified_by_and_more"),
    ]

    initial = True

    dependencies = [
        ("categories", "0002_auto_20140820_1415"),
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, help_text="When this item was originally created"),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, help_text="When this item was last modified")),
                ("title", models.CharField(help_text="The title for this story", max_length=255)),
                ("featured", models.BooleanField(default=False, help_text="Whether this story is featured")),
                ("content", models.TextField(help_text="The body of text for the story")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Any image that should be displayed with this story",
                        null=True,
                        upload_to="stories",
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        blank=True,
                        help_text="The id of the YouTube video that should be linked to this story",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Any tags for this story, separated by spaces, can be used to do more advanced filtering, optional",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        help_text="The organization this story belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orgs.org",
                    ),
                ),
                ("summary", models.TextField(blank=True, help_text="The summary for the story", null=True)),
            ],
            options={
                "verbose_name_plural": "Stories",
            },
        ),
        migrations.RunPython(
            code=populate_story_summary,
            reverse_code=noop,
        ),
        migrations.AddField(
            model_name="story",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="The category for this story",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="categories.category",
            ),
        ),
        migrations.RunPython(
            code=add_category_to_current_stories,
            reverse_code=noop,
        ),
        migrations.CreateModel(
            name="StoryImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this item is active, use this instead of deleting"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, help_text="When this item was originally created"),
                ),
                ("modified_on", models.DateTimeField(auto_now=True, help_text="When this item was last modified")),
                ("name", models.CharField(help_text="The name to describe this image", max_length=64)),
                ("image", models.ImageField(help_text="The image file to use", upload_to="stories")),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        help_text="The story to associate to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            code=move_images,
            reverse_code=noop,
        ),
        migrations.RemoveField(
            model_name="story",
            name="image",
        ),
        migrations.AlterField(
            model_name="story",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="video_id",
            field=models.CharField(
                blank=True,
                help_text="The id of the YouTube video that should be linked to this story (this is the text that comes afer v= and before & in the YouTube URL)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storyimage",
            name="story",
            field=models.ForeignKey(
                help_text="The story to associate to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="images",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="audio_link",
            field=models.URLField(
                blank=True, help_text="A link to an mp3 file to publish on this story", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="written_by",
            field=models.CharField(blank=True, help_text="The writer of the story", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="created_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was originally created",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="modified_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was last modified",
            ),
        ),
        migrations.AlterField(
            model_name="storyimage",
            name="created_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was originally created",
            ),
        ),
        migrations.AlterField(
            model_name="storyimage",
            name="modified_on",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                help_text="When this item was last modified",
            ),
        ),
        migrations.AlterField(
            model_name="storyimage",
            name="image",
            field=models.ImageField(
                help_text="The image file to use",
                upload_to=functools.partial(dash.utils.generate_file_path, *("stories",), **{}),
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="The PDF report to attach",
                null=True,
                upload_to=functools.partial(dash.utils.generate_file_path, *("story_attachments",), **{}),
                validators=[dash.stories.models.validate_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="storyimage",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="storyimage",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
