# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20180312_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='backend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.OrgBackend'),
        ),
    ]
