name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        python-version: ["3.10.x", "3.11.x", "3.12.x"]
        django-version: ["5.0.x", "5.1.x"]
    env:
      redis-version: "6.2"
      pg-version: "15"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Redis
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: ${{ env.redis-version }}

      - name: Install PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: ${{ env.pg-version }}
          postgresql db: dash
          postgresql user: dash
          postgresql password: rapidpro

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true

      - name: Initialize environment
        run: |
          poetry install
          poetry add django==${{ matrix.django-version }}

      - name: Run pre-test checks
        run: |
          sudo apt-get install gettext
          poetry run python ./code_check.py --debug

      - name: Run tests
        run: |
          poetry run coverage run manage.py test dash test_runner --verbosity=2
          poetry run coverage report -i
          poetry run coverage xml

      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  release:
    name: Release
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.x"

      - name: Publish release
        run: |
          python -m pip install -U pip poetry
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
